# Generated by Django 5.0.2 on 2025-02-10 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('discipline', models.CharField(db_index=True, max_length=200)),
                ('sub_discipline', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['discipline', 'sub_discipline'], name='api_departm_discipl_da7a2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('gender', models.CharField(db_index=True, max_length=50, null=True)),
                ('would_take_again_percent', models.FloatField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.FloatField(db_index=True, default=0.0)),
                ('flag_status', models.CharField(db_index=True, max_length=50, null=True)),
                ('class_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('helpful_rating', models.FloatField(db_index=True, null=True)),
                ('clarity_rating', models.FloatField(db_index=True, null=True)),
                ('difficulty_rating', models.FloatField(db_index=True, null=True)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('is_for_credit', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('processed_comment', models.TextField(null=True)),
                ('sentiment', models.IntegerField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('ACADEMIC', 'Academic Staff')], default='ACADEMIC', max_length=10)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['department', 'gender'], name='api_profess_departm_bafa18_idx'),
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['last_name', 'first_name'], name='api_profess_last_na_22b86d_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['professor', 'created_at'], name='api_rating_profess_7ea0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['avg_rating', 'helpful_rating', 'clarity_rating'], name='api_rating_avg_rat_3bdb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='sentiment',
            index=models.Index(fields=['professor', 'sentiment'], name='api_sentime_profess_b5feff_idx'),
        ),
        migrations.AddIndex(
            model_name='sentiment',
            index=models.Index(fields=['professor', 'created_at'], name='api_sentime_profess_fe97ba_idx'),
        ),
    ]
