# Generated by Django 5.0.2 on 2025-02-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='class_name',
        ),
    ]
