# Generated by Django 5.0.2 on 2025-02-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='vader_compound',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='vader_negative',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='vader_neutral',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='vader_positive',
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='sentiment',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
