# Generated by Django 5.0.2 on 2025-02-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rating_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='department',
        ),
        migrations.AddField(
            model_name='userrole',
            name='discipline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
