# Generated by Django 5.0.2 on 2025-02-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userrole_department_userrole_discipline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='api_rating_avg_rat_3bdb7b_idx',
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['avg_rating', 'helpful_rating', 'clarity_rating', 'difficulty_rating'], name='api_rating_avg_rat_d0f0f6_idx'),
        ),
    ]
