# Generated by Django 5.0.2 on 2025-02-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='negative_terms',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='positive_terms',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='vader_compound',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='vader_negative',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='vader_neutral',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='vader_positive',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='sentiment',
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
