# Generated by Django 5.0.2 on 2025-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_professor_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveIndex(
            model_name='professor',
            name='api_profess_departm_bafa18_idx',
        ),
        migrations.RemoveIndex(
            model_name='professor',
            name='api_profess_last_na_22b86d_idx',
        ),
        migrations.AlterField(
            model_name='professor',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_id',
            field=models.CharField(default='PID000000', max_length=50, unique=True),
        ),
    ]
