services:
  backend:
    build: ./backend
    command: gunicorn faireval.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=faireval.settings
      - SECRET_KEY=${DJANGO_SECRET_KEY}

      - DB_HOST=host.docker.internal
      - DB_NAME=fair_eval_sys_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
      - ALLOWED_HOSTS=localhost

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data: